### ISSUE TITLE
Ember 1.8.0 compatibility

### ISSUE THREAD

**Issue by RyanHirsch** [instructure/ic-tabs#10]
With the release of ember 1.8.0 the tab panels don't seem to be rendering anymore. There are no errors being displayed so I don't quite know what is causing the issue.

http://emberjs.jsbin.com/yiqefa/3 is a jsbin running 1.8.0 with the example ic-tabs

I would be more than happy to try and fix the issue if I knew what was going wrong.

**Comment by atsjj** [comment]
Reporting the same issue.

I'm looking into the component now; will issue a PR if I can fix it.

**Comment by atsjj** [comment]
I have patched this on my fork, but have yet to PR my changes. Read the commit log if you're interested. You'll need to compile the project for an updated dist.

https://github.com/atsjj/ic-tabs/tree/ember-1.8.0-compatibility

**Comment by quaertym** [comment]
@atsjj any updates?

**Comment by atsjj** [comment]
@quaertym this is on my board for the week. I'll be pushing changes on my branch in the coming days!

**Comment by quaertym** [comment]
@atsjj Will you send a PR?

**Comment by samselikoff** [comment]
Ran into this today as well. I thought 1.8 is backwards compatible? Does this mean ic-tabs uses private APIs?

**Comment by quaertym** [comment]
@samselikoff No, it does not use private APIs. Just the order `didInsertElement` is fired changed for child views in `1.8`.  

From breaking changes section of [Ember 1.8 release blog post](http://emberjs.com/blog/2014/10/26/ember-1-8-0-released.html#toc_breaking-changes):

> didInsertElement is now always called on a child view before it is called on a rendering parent view. In previous releases of Ember.js didInsertElement would often be called first on a parent view, however this behavior was inconsistent. In general, developers are encouraged to consider scheduling work into the afterRender queue if it includes accessing DOM not immediately under that view's control.

**Comment by samselikoff** [comment]
@quaertym gotcha, thanks.

I'm having a hard time building a dist of @atsjj's branch. Any chance you know what's going on here?

```
➜  ic-tabs git:(master) ✗ sh script/build
# running script/build

~/.nvm/v0.10.31/lib/node_modules/broccoli-cli/node_modules/resolve/lib/sync.js:32
    throw new Error("Cannot find module '" + x + "' from '" + y + "'");
          ^
Error: Cannot find module 'broccoli' from '~/my-app/bower_components/ic-tabs'
    at Function.module.exports [as sync] (~/.nvm/v0.10.31/lib/node_modules/broccoli-cli/node_modules/resolve/lib/sync.js:32:11)
    at Object.<anonymous> (~/.nvm/v0.10.31/lib/node_modules/broccoli-cli/bin/broccoli:7:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by quaertym** [comment]
@samselikoff What I do is to install ic-tabs via bower(this repo) and fix that one problematic line.

**Comment by samselikoff** [comment]
@quaertym thanks. That seems like a solution for now.
