### ISSUE TITLE
Use with Ember CLI

### ISSUE THREAD

**Issue by samselikoff** [instructure/ic-tabs#8]
I've been trying to get ic-tabs into my Ember CLI project without success. I tried importing it in the Brocfile a la the ic-ajax example, but I kept getting errors.

Has anybody used ic-tabs with Ember CLI?

**Comment by RyanHirsch** [comment]
I am also trying to get this working and had no success.  I've tried adding the following to my Brocfile.js

``` js
app.import('bower_components/ic-styled/main.js');
app.import('bower_components/ic-tabs/dist/named-amd/main.js', {
    exports: {
        'ic-tabs': [
            'default',
            'tab-list',
            'tab-panel',
            'tab',
            'tabs',
            'tabs-css'
        ]
    }
});
```

I am on ember-cli v0.0.42

**Comment by samselikoff** [comment]
I ended up importing the globals:

``` js
app.import('bower_components/ic-styled/main.js');
app.import('bower_components/ic-tabs/dist/globals/main.js');
```
